package com.zenit.bryan.prestatec;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteException;
import android.database.sqlite.SQLiteOpenHelper;


public class baseDatos extends SQLiteOpenHelper {
    String error;
    public baseDatos(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        try{
           db.execSQL("CREATE TABLE RELACIONES(IDR INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, TIPO VARCHAR(100) NOT NULL)");
           db.execSQL("CREATE TABLE CATALOGO(IDCAT INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, TIPO VARCHAR(100) NOT NULL)");

           db.execSQL("CREATE TABLE CONTACTOS(IDCON INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, NOMBRE VARCHAR(255), RELACION INT, TELEFONO VARCHAR(20), FOREIGN KEY (RELACION) REFERENCES RELACIONES(IDR))");

            db.execSQL("CREATE TABLE PRESTAMOS(IDP INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, PRESTATARIO INT NOT NULL, TIPO INT NOT NULL, OBJETO VARCHAR(255) NOT NULL, ESTADO VARCHAR(30) NOT NULL,OBSERVACIONES VARCHAR(255),FPRESTAMO VARCHAR(20), FDEVUELTO VARCHAR(20), FOREIGN KEY (PRESTATARIO) REFERENCES CONTACTOS(IDCON) ON DELETE CASCADE,FOREIGN KEY (TIPO) REFERENCES CATALOGO(IDCAT) ON DELETE CASCADE)");
           db.execSQL("CREATE TABLE REGRESADOS(IDREG INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, PRESTATARIO VARCHAR(255) NOT NULL, TIPO VARCHAR(100) NOT NULL, OBJETO VARCHAR(255) NOT NULL,OBSERVACIONES VARCHAR(255),FPRESTAMO VARCHAR(20), FENTREGADO VARCHAR(20))");

           db.execSQL("INSERT INTO RELACIONES(TIPO) VALUES('AMIGO')");
           db.execSQL("INSERT INTO CATALOGO(TIPO) VALUES('ROPA')");
            db.execSQL("INSERT INTO CONTACTOS(NOMBRE,RELACION,TELEFONO) VALUES('KERVIN',1,'34555')");

            db.execSQL("INSERT INTO PRESTAMOS(PRESTATARIO,TIPO,OBJETO,ESTADO,OBSERVACIONES,FPRESTAMO,FDEVUELTO) VALUES(1,1,'PANTALON2','PENDIENTE','NINGUNA','2015-02-03','2015-02-03')");

            db.execSQL("INSERT INTO PRESTAMOS(PRESTATARIO,TIPO,OBJETO,ESTADO,OBSERVACIONES,FPRESTAMO,FDEVUELTO) VALUES(1,1,'PANTALON','PENDIENTE','NNN','2015-02-03','2015-02-03')");
            db.execSQL("INSERT INTO REGRESADOS(PRESTATARIO,TIPO,OBJETO,OBSERVACIONES,FPRESTAMO,FENTREGADO) VALUES('LUIS','ROPA','PANTALON','PENDIENTE','2015-02-03','2015-02-03')");
        }
        catch(SQLiteException ex)
        {
            error= ex.getMessage();
        }
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
